# Generated by Django 3.0.8 on 2020-07-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.CharField(choices=[('sport', 'sport'), ('concerts', 'concerts'), ('thearte', 'thearte'), ('stand up', 'stand up'), ('for-children', 'for-children'), ('cinema', 'cinema'), ('others', 'others')], max_length=20),
        ),
    ]
