# Generated by Django 3.0.8 on 2020-07-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200708_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FileField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
