# Generated by Django 3.0.8 on 2020-07-23 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedtickets',
            name='email',
        ),
        migrations.RemoveField(
            model_name='purchasedtickets',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='purchasedtickets',
            name='last_name',
        ),
        migrations.AddField(
            model_name='purchasedtickets',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
