# Generated by Django 3.0.8 on 2020-07-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200723_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tickets', models.ManyToManyField(related_name='order_tickets', to='events.Ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='PurchasedTickets',
        ),
    ]
