# Generated by Django 3.0.8 on 2020-07-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200724_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtickets',
            old_name='count',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='count',
            new_name='quantity',
        ),
    ]
