# Generated by Django 3.0.8 on 2020-07-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200726_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertickets',
            name='tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='events.OrderTickets'),
            preserve_default=False,
        ),
    ]
