# Generated by Django 3.0.8 on 2020-07-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200726_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertickets',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
