# Generated by Django 3.0.8 on 2020-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200726_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertickets',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
