# Generated by Django 3.0.8 on 2020-07-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_ticket_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='paid',
        ),
        migrations.AddField(
            model_name='ordertickets',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
