# Generated by Django 3.0.8 on 2020-07-30 17:13

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_ordertickets_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertickets',
            name='date',
        ),
        migrations.AddField(
            model_name='ordertickets',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
