# Generated by Django 3.0.8 on 2020-07-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20200730_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertickets',
            name='included',
            field=models.BooleanField(default=False),
        ),
    ]
