  version: '3'
      
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: db

    redis:
      image: "redis:alpine"
      container_name: redis
    
    elasticsearch:
      environment: 
        - discovery.type=single-node
      image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
      ports:
        - "9200:9200"
        - "9300:9300"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
        interval: 30s
        timeout: 10s
        retries: 5
      container_name: elasticsearch

    web:
      env_file:
        - web-variables.env
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - db
        - elasticsearch
      container_name: web

    celery:
      build: .
      command: celery -A tickets worker -l info
      volumes:
        - .:/app
      depends_on: 
        - db
        - redis
      container_name: celery